using BLite.Core.Collections;
using BLite.Core.Encryption;
using BLite.Core.KeyValue;
using BLite.Core.Metadata;
using BLite.Core.Storage;
using BLite.Core.Transactions;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BLite.Bson;

namespace BLite.Core;

/// <summary>
/// Base class for database contexts.
/// Inherit and add DocumentCollection{T} properties for your entities.
/// Use partial class for Source Generator integration.
/// </summary>
public abstract partial class DocumentDbContext : IDocumentDbContext
{
    protected readonly StorageEngine _storage;
    internal readonly CDC.ChangeStreamDispatcher _cdc;
    private readonly FreeSpaceIndexProvider _freeSpaceIndexes;
    private readonly BLiteKvStore _kvStore;
    // Optional: stores the file-system path supplied to path-based constructors.
    // Null when the context was built from a pre-existing StorageEngine (e.g. in-memory).
    // Surfaced via the internal Storage / DatabaseFilePath / FreeSpaceIndexes accessors
    // consumed by GDPR extension methods (GdprDocumentDbContextExtensions).
    private readonly string? _databasePath;
    // Owned coordinator (master-key/HKDF mode). Disposed with the context so that the
    // master key bytes are zeroed when the context is disposed.
    private readonly EncryptionCoordinator? _ownedCoordinator;
    protected bool _disposed;

    /// <summary>
    /// Parameterless constructor reserved for remote context subclasses generated by
    /// BLite.Client.SourceGenerators. Do <b>not</b> use this constructor for local
    /// embedded databases — the storage engine will not be initialised.
    /// </summary>
    protected DocumentDbContext()
    {
        _storage = null!;
        _cdc = null!;
        _freeSpaceIndexes = null!;
        _kvStore = null!;
        _model = new System.Collections.Generic.Dictionary<Type, object>();
        InitializeCollections();
    }

    /// <summary>
    /// Creates a new database context with default configuration.
    /// Auto-detects the page size for existing database files.
    /// </summary>
    protected DocumentDbContext(string databasePath)
        : this(databasePath, PageFileConfig.DetectFromFile(databasePath) ?? PageFileConfig.Default, null)
    {
    }

    /// <summary>
    /// Creates a new database context with custom page configuration.
    /// </summary>
    protected DocumentDbContext(string databasePath, PageFileConfig config)
        : this(databasePath, config, null)
    {
    }

    /// <summary>
    /// Creates a new database context with custom Key-Value store options.
    /// </summary>
    protected DocumentDbContext(string databasePath, BLiteKvOptions kvOptions)
        : this(databasePath, PageFileConfig.Default, kvOptions)
    {
    }

    /// <summary>
    /// Creates a new database context with custom page and Key-Value store configuration.
    /// </summary>
    protected DocumentDbContext(string databasePath, PageFileConfig config, BLiteKvOptions? kvOptions)
    {
        if (string.IsNullOrWhiteSpace(databasePath))
            throw new ArgumentNullException(nameof(databasePath));

        _databasePath = databasePath;
        _storage = new StorageEngine(databasePath, config);
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        // Initialize model before collections
        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
        RunGdprStrictValidation(kvOptions);
    }

    /// <summary>
    /// Creates a new database context with transparent AES-256-GCM encryption at rest.
    /// <para>
    /// Mirrors <see cref="BLiteEngine(string, CryptoOptions, BLiteKvOptions?, PageFileConfig?)"/>
    /// so the typed and dynamic modes expose a uniform encryption API surface.
    /// </para>
    /// </summary>
    /// <param name="databasePath">Path to the database file (or main file in server mode).</param>
    /// <param name="crypto">
    /// Encryption configuration. Passphrase mode (PBKDF2 single-file) or master-key mode
    /// (HKDF multi-file via <see cref="CryptoOptions.FromMasterKey(System.ReadOnlySpan{byte})"/>).
    /// In master-key mode the context owns the underlying coordinator and zeros the master
    /// key on <see cref="Dispose"/>.
    /// </param>
    /// <param name="kvOptions">Optional Key-Value store configuration.</param>
    /// <param name="baseConfig">
    /// Optional base page configuration. Used as the base layout for master-key (server) mode;
    /// ignored in passphrase mode (which always uses single-file <see cref="PageFileConfig.Default"/>).
    /// </param>
    protected DocumentDbContext(string databasePath, CryptoOptions crypto, BLiteKvOptions? kvOptions = null, PageFileConfig? baseConfig = null)
    {
        if (string.IsNullOrWhiteSpace(databasePath))
            throw new ArgumentNullException(nameof(databasePath));
        if (crypto == null)
            throw new ArgumentNullException(nameof(crypto));

        _databasePath = databasePath;

        PageFileConfig config;
        if (crypto.IsMasterKeyMode)
        {
            _ownedCoordinator = new EncryptionCoordinator(crypto);
            config = PageFileConfig.Server(databasePath, baseConfig) with
            {
                CryptoProvider = _ownedCoordinator.CreateForMainFile()
            };
        }
        else
        {
            // Do NOT use DetectFromFile here — the encrypted file begins with a 64-byte crypto
            // header, not a page header.
            config = PageFileConfig.Default with
            {
                CryptoProvider = new AesGcmCryptoProvider(crypto)
            };
        }

        _storage = new StorageEngine(databasePath, config);
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
        RunGdprStrictValidation(kvOptions);
    }
    /// the coordinator path explicitly. Caller-owned coordinator (not disposed by the context).
    /// </summary>
    internal DocumentDbContext(string databasePath, EncryptionCoordinator coordinator, PageFileConfig? baseConfig = null, BLiteKvOptions? kvOptions = null)
        : this(
            databasePath,
            PageFileConfig.Server(
                databasePath ?? throw new ArgumentNullException(nameof(databasePath)),
                baseConfig) with
            {
                CryptoProvider = (coordinator ?? throw new ArgumentNullException(nameof(coordinator))).CreateForMainFile()
            },
            kvOptions)
    {
    }

    /// <summary>
    /// Creates a database context backed by a pre-built <see cref="StorageEngine"/>.
    /// Use this constructor to supply a custom backend, such as
    /// <see cref="MemoryPageStorage"/> for in-memory or WASM scenarios.
    /// <para>
    /// Example — in-memory context:
    /// <code>
    /// var pageStorage = new MemoryPageStorage(16384);
    /// pageStorage.Open();
    /// var wal = new MemoryWriteAheadLog();
    /// var engine = new StorageEngine(pageStorage, wal);
    /// var ctx = new MyDbContext(engine);
    /// </code>
    /// </para>
    /// </summary>
    protected DocumentDbContext(StorageEngine storage, BLiteKvOptions? kvOptions = null)
    {
        _storage = storage ?? throw new ArgumentNullException(nameof(storage));
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
        RunGdprStrictValidation(kvOptions);
    }

    /// <summary>
    /// Provides access to the embedded Key-Value store that shares the same database file.
    /// </summary>
    public IBLiteKvStore KvStore
    {
        get
        {
            if (_disposed) throw new ObjectDisposedException(GetType().Name);
            return _kvStore;
        }
    }

    // ── Internal accessors used by GDPR extensions (BLite.Core.GDPR) ─────────
    // These mirror the equivalent surface on BLiteEngine so that
    // ExportSubjectDataAsync / InspectDatabase work uniformly on both
    // engine-first (BLiteEngine) and code-first (DocumentDbContext) flows.

    /// <summary>The underlying storage engine. Internal-only.</summary>
    internal StorageEngine Storage => _storage;

    /// <summary>
    /// File-system path supplied to a path-based constructor, or <see langword="null"/>
    /// when the context was built from a pre-existing <see cref="StorageEngine"/>
    /// (e.g. in-memory backends).
    /// </summary>
    internal string? DatabaseFilePath => _databasePath;

    /// <summary>Free-space index provider used to instantiate transient dynamic collections.</summary>
    internal FreeSpaceIndexProvider FreeSpaceIndexes => _freeSpaceIndexes;

    /// <summary>
    /// Opens a new isolated session backed by this context's storage engine.
    /// Each session carries its own independent transaction context, enabling
    /// concurrent operations from multiple callers on the same database.
    /// </summary>
    public BLiteSession OpenSession()
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        return new BLiteSession(_storage, _freeSpaceIndexes);
    }

    /// <summary>
    /// Creates a document collection bound to an explicit <paramref name="holder"/>.
    /// Use together with sessions from <see cref="OpenSession"/> so that the resulting
    /// collection's operations run inside the session's independent transaction context.
    /// </summary>
    [RequiresDynamicCode("Collection creation uses Expression.Compile() via CollectionIndexManager and ValueConverterRegistry which require dynamic code generation.")]
    [RequiresUnreferencedCode("Index creation uses reflection to access type members. Ensure all entity types and their members are preserved.")]
    public IDocumentCollection<TId, T> CreateSessionCollection<TId, T>(IDocumentMapper<TId, T> mapper, ITransactionHolder holder)
        where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        string? customName = null;
        EntityTypeBuilder<T>? builder = null;

        if (_model.TryGetValue(typeof(T), out var builderObj))
        {
            builder = builderObj as EntityTypeBuilder<T>;
            customName = builder?.CollectionName;
        }

        var collection = new DocumentCollection<TId, T>(_storage, holder, mapper, customName, _freeSpaceIndexes.GetIndex());

        if (builder != null)
        {
            if (builder.PropertyConverters.Count > 0)
                collection.SetConverterRegistry(new ValueConverterRegistry(builder.PropertyConverters));

            foreach (var indexBuilder in builder.Indexes)
                collection.ApplyIndexBuilder(indexBuilder);

            if (builder.TimeSeriesTtlField != null && builder.TimeSeriesRetention.HasValue)
                collection.SetTimeSeries(builder.TimeSeriesTtlField, builder.TimeSeriesRetention.Value);

            if (builder.RetentionPolicy != null)
                collection.SetRetentionPolicy(builder.RetentionPolicy);
        }

        return collection;
    }

    protected virtual void InitializeCollections()
    {
        // Derived classes can override to initialize collections
    }

    /// <summary>
    /// Drops any collections that exist in the underlying database but are not
    /// registered in this context. Called automatically at construction time so
    /// the database stays in sync with the schema defined by the <see cref="DocumentDbContext"/>.
    /// </summary>
    private void DropOrphanCollections()
    {
        if (_storage == null) return; // parameterless remote-context constructor

        // Build the set of collection names that this context knows about.
        var registeredNames = new HashSet<string>(
            _mapperRegistry.Values.Select(m => m.CollectionName),
            StringComparer.OrdinalIgnoreCase);

        foreach (var metadata in _storage.GetAllCollectionsMetadata())
        {
            if (registeredNames.Contains(metadata.Name)) continue;

            // Orphan — free its pages, delete its metadata, and remove any per-collection file.
            _storage.FreeCollectionPages(metadata.Name);
            _storage.DeleteCollectionMetadata(metadata.Name);
            _storage.DropCollectionFile(metadata.Name);
        }
    }

    /// <summary>
    /// Computes the effective GDPR mode for this context (engine-wide default or the
    /// strictest per-entity mode registered in <see cref="OnModelCreating"/>) and
    /// delegates to <see cref="GDPR.GdprStrictValidator.Apply"/>.
    /// Called at the end of every real (non-parameterless) constructor.
    /// </summary>
    private void RunGdprStrictValidation(BLiteKvOptions? kvOptions)
    {
        // Engine-wide default.
        var effectiveMode = kvOptions?.DefaultGdprMode ?? GDPR.GdprMode.None;

        // Escalate to Strict if any entity in the model has HasGdprMode(Strict).
        if (effectiveMode != GDPR.GdprMode.Strict && _model != null)
        {
            foreach (var builderObj in _model.Values)
            {
                if (builderObj is Metadata.IGdprModeAccessor accessor &&
                    accessor.GdprMode == GDPR.GdprMode.Strict)
                {
                    effectiveMode = GDPR.GdprMode.Strict;
                    break;
                }
            }
        }

        GDPR.GdprStrictValidator.Apply(_storage, effectiveMode, kvOptions);
    }

    private readonly IReadOnlyDictionary<Type, object> _model;
    private readonly List<IDocumentMapper> _registeredMappers = new();

    // Per-collection delegates registered in CreateCollection<TId, T> (called during
    // InitializeCollections, which runs on the construction thread).  These are read-only
    // after construction; no concurrent mutation occurs.
    private readonly Dictionary<Type, IDocumentMapper> _mapperRegistry = new();
    private readonly Dictionary<Type, Func<CancellationToken, Task<int>>> _truncateCallbacks = new();

    /// <summary>
    /// Override to configure the model using Fluent API.
    /// 
    /// This method is used in two phases:
    /// 1. Compile-time: The Source Generator analyzes this method to extract entity configurations
    ///    (collection names, keys, converters, etc.) and embeds them into generated mappers.
    /// 2. Runtime: Configuration is used to dynamically apply indexes to collections.
    /// 
    /// Configuration priority: ModelBuilder > Attributes > Conventions
    /// 
    /// Example:
    ///   modelBuilder.Entity&lt;Order&gt;()
    ///       .ToCollection("orders")
    ///       .HasIndex(x => x.Status);
    ///   
    ///   modelBuilder.Entity&lt;Order&gt;()
    ///       .Property(x => x.Id)
    ///       .HasConversion&lt;OrderIdConverter&gt;();
    /// </summary>
    protected virtual void OnModelCreating(ModelBuilder modelBuilder)
    {
    }

    /// <summary>
    /// Helper to create a DocumentCollection instance with custom TId.
    /// Used by derived classes in InitializeCollections for typed primary keys.
    /// </summary>
    [RequiresDynamicCode("Collection creation uses Expression.Compile() via CollectionIndexManager and ValueConverterRegistry which require dynamic code generation.")]
    [RequiresUnreferencedCode("Index creation uses reflection to access type members. Ensure all entity types and their members are preserved.")]
    protected virtual IDocumentCollection<TId, T> CreateCollection<TId, T>(IDocumentMapper<TId, T> mapper)
        where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        string? customName = null;
        EntityTypeBuilder<T>? builder = null;

        if (_model.TryGetValue(typeof(T), out var builderObj))
        {
            builder = builderObj as EntityTypeBuilder<T>;
            customName = builder?.CollectionName;
        }

        _registeredMappers.Add(mapper);
        var collection = new DocumentCollection<TId, T>(_storage, this, mapper, customName, _freeSpaceIndexes.GetIndex());

        // Apply configurations from ModelBuilder
        if (builder != null)
        {
            // Register value converters so the query engine can convert ValueObjects
            // to BSON primitives at query-plan time.
            if (builder.PropertyConverters.Count > 0)
                collection.SetConverterRegistry(new ValueConverterRegistry(builder.PropertyConverters));

            foreach (var indexBuilder in builder.Indexes)
            {
                collection.ApplyIndexBuilder(indexBuilder);
            }

            if (builder.TimeSeriesTtlField != null && builder.TimeSeriesRetention.HasValue)
                collection.SetTimeSeries(builder.TimeSeriesTtlField, builder.TimeSeriesRetention.Value);

            if (builder.RetentionPolicy != null)
                collection.SetRetentionPolicy(builder.RetentionPolicy);
        }

        _storage.RegisterMappers(_registeredMappers);

        // Register per-type delegates so TruncateCollectionAsync<T>() can operate
        // without reflection.  Populated once during InitializeCollections (single-threaded
        // constructor path) and only read on the hot path afterwards.
        _mapperRegistry[typeof(T)] = mapper;
        var col = collection;                                    // close over typed instance
        _truncateCallbacks[typeof(T)] = ct => col.TruncateAsync(ct);

        return collection;
    }

    /// <summary>
    /// Gets the document collection for the specified entity type using an ObjectId as the key.
    /// </summary>
    /// <typeparam name="T">The type of entity to retrieve the document collection for. Must be a reference type.</typeparam>
    /// <returns>An <see cref="IDocumentCollection{T}"/> instance for the specified entity type.</returns>
    public IDocumentCollection<ObjectId, T> Set<T>() where T : class => Set<ObjectId, T>();

    /// <summary>
    /// Gets a collection for managing documents of type T, identified by keys of type TId.
    /// Override is generated automatically by the Source Generator for partial DbContext classes.
    /// </summary>
    /// <typeparam name="TId">The type of the unique identifier for documents in the collection.</typeparam>
    /// <typeparam name="T">The type of the document to be managed. Must be a reference type.</typeparam>
    /// <returns>An <see cref="IDocumentCollection{TId,T}"/> instance for performing operations on documents of type T.</returns>
    public virtual IDocumentCollection<TId, T> Set<TId, T>() where T : class
    {
        throw new InvalidOperationException($"No collection registered for entity type '{typeof(T).Name}' with key type '{typeof(TId).Name}'.");
    }

    /// <summary>
    /// Deletes all documents in the collection for <typeparamref name="T"/> and clears all secondary indexes.
    /// The collection structure (schema, indexes, metadata) is preserved and the collection
    /// is immediately usable after the operation completes.
    /// </summary>
    /// <returns>Number of documents deleted.</returns>
    public async Task<int> TruncateCollectionAsync<T>(CancellationToken ct = default) where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        if (!_truncateCallbacks.TryGetValue(typeof(T), out var truncate))
            throw new InvalidOperationException($"No collection registered for entity type '{typeof(T).Name}'.");

        return await truncate(ct).ConfigureAwait(false);
    }

    // ── Metrics ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Enables the metrics subsystem. After this call, the engine starts collecting
    /// performance counters. Safe to call multiple times — idempotent.
    /// </summary>
    public void EnableMetrics(Metrics.MetricsOptions? options = null)
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        _storage.EnsureMetrics();
    }

    /// <summary>
    /// Returns an immutable point-in-time snapshot of performance counters,
    /// or <c>null</c> if <see cref="EnableMetrics"/> has not been called.
    /// </summary>
    public Metrics.MetricsSnapshot? GetMetrics()
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        return _storage.MetricsDispatcher?.GetSnapshot();
    }

    /// <summary>
    /// Returns an <see cref="IObservable{T}"/> that emits a <see cref="Metrics.MetricsSnapshot"/>
    /// at the given <paramref name="interval"/> (default 1 s).
    /// Enables the metrics subsystem automatically if not yet enabled.
    /// </summary>
    public IObservable<Metrics.MetricsSnapshot> WatchMetrics(TimeSpan? interval = null)
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        var dispatcher = _storage.EnsureMetrics();
        return new Metrics.BLiteMetricsObservable(dispatcher, interval ?? TimeSpan.FromSeconds(1));
    }

    // ── Audit ─────────────────────────────────────────────────────────────────

    /// <summary>
    /// Configures the audit trail subsystem.
    /// <para>
    /// Call this method immediately after constructing the context to activate audit hooks.
    /// All hooks are guarded by a <see langword="null"/>-check so there is zero overhead
    /// when audit is not configured.
    /// </para>
    /// </summary>
    /// <param name="options">Audit configuration, including the optional sink, metrics, and thresholds.</param>
    public void ConfigureAudit(Audit.BLiteAuditOptions options)
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        _storage.ConfigureAudit(options ?? throw new ArgumentNullException(nameof(options)));
    }

    /// <summary>
    /// In-process audit metrics. Non-<see langword="null"/> only when
    /// <see cref="Audit.BLiteAuditOptions.EnableMetrics"/> is <see langword="true"/> and
    /// <see cref="ConfigureAudit"/> has been called.
    /// </summary>
    public Audit.BLiteMetrics? AuditMetrics => _storage?.AuditMetrics;

    public void Dispose()
    {
        if (_disposed)
            return;

        _disposed = true;

        _storage?.Dispose();
        _cdc?.Dispose();
        _ownedCoordinator?.Dispose();

        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Creates a new caller-owned transaction.
    /// The caller must pass this transaction to every collection method and
    /// call <see cref="SaveChangesAsync(ITransaction, CancellationToken)"/> to commit.
    /// </summary>
    public ITransaction BeginTransaction()
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        return _storage.BeginTransaction();
    }

    /// <summary>
    /// Creates a new caller-owned transaction asynchronously.
    /// </summary>
    public ValueTask<ITransaction> BeginTransactionAsync(CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        ct.ThrowIfCancellationRequested();
        return new ValueTask<ITransaction>(_storage.BeginTransaction(IsolationLevel.ReadCommitted));
    }

    /// <summary>
    /// Creates an ephemeral read transaction for internal use by collection read paths.
    /// Write paths create their own auto-commit transactions when no caller-owned tx is provided.
    /// </summary>
    public ValueTask<ITransaction> GetCurrentTransactionOrStartAsync()
    {
        return new ValueTask<ITransaction>(_storage.BeginTransaction(IsolationLevel.ReadCommitted));
    }

    /// <summary>
    /// No-op when called without a transaction.
    /// Exists for API compatibility — auto-commit write operations commit immediately.
    /// </summary>
    public ValueTask SaveChangesAsync(CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        return default;
    }

    /// <summary>
    /// Commits a caller-owned transaction created by <see cref="BeginTransactionAsync"/>.
    /// </summary>
    public async ValueTask SaveChangesAsync(ITransaction transaction, CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        if (transaction == null)
            throw new ArgumentNullException(nameof(transaction));
        await transaction.CommitAsync(ct);
    }
}
