using BLite.Core.Collections;
using BLite.Core.Encryption;
using BLite.Core.KeyValue;
using BLite.Core.Metadata;
using BLite.Core.Storage;
using BLite.Core.Transactions;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BLite.Bson;

namespace BLite.Core;

/// <summary>
/// Base class for database contexts.
/// Inherit and add DocumentCollection{T} properties for your entities.
/// Use partial class for Source Generator integration.
/// </summary>
public abstract partial class DocumentDbContext : IDocumentDbContext
{
    protected readonly StorageEngine _storage;
    internal readonly CDC.ChangeStreamDispatcher _cdc;
    private readonly FreeSpaceIndexProvider _freeSpaceIndexes;
    private readonly BLiteKvStore _kvStore;
    // Non-null only when this context created the coordinator internally (BLiteEngineOptions path).
    // Null when an external coordinator was passed in (caller retains ownership).
    private readonly EncryptionCoordinator? _coordinator;
    protected bool _disposed;

    /// <summary>
    /// Parameterless constructor reserved for remote context subclasses generated by
    /// BLite.Client.SourceGenerators. Do <b>not</b> use this constructor for local
    /// embedded databases — the storage engine will not be initialised.
    /// </summary>
    protected DocumentDbContext()
    {
        _storage = null!;
        _cdc = null!;
        _freeSpaceIndexes = null!;
        _kvStore = null!;
        _model = new System.Collections.Generic.Dictionary<Type, object>();
        InitializeCollections();
    }

    /// <summary>
    /// Creates a new database context with default configuration.
    /// Auto-detects the page size for existing database files.
    /// </summary>
    protected DocumentDbContext(string databasePath)
        : this(databasePath, PageFileConfig.DetectFromFile(databasePath) ?? PageFileConfig.Default, null)
    {
    }

    /// <summary>
    /// Creates a new database context with custom page configuration.
    /// </summary>
    protected DocumentDbContext(string databasePath, PageFileConfig config)
        : this(databasePath, config, null)
    {
    }

    /// <summary>
    /// Creates a new database context with custom Key-Value store options.
    /// </summary>
    protected DocumentDbContext(string databasePath, BLiteKvOptions kvOptions)
        : this(databasePath, PageFileConfig.Default, kvOptions)
    {
    }

    /// <summary>
    /// Creates a new database context with custom page and Key-Value store configuration.
    /// </summary>
    protected DocumentDbContext(string databasePath, PageFileConfig config, BLiteKvOptions? kvOptions)
    {
        if (string.IsNullOrWhiteSpace(databasePath))
            throw new ArgumentNullException(nameof(databasePath));

        _storage = new StorageEngine(databasePath, config);
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        // Initialize model before collections
        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
    }

    /// <summary>
    /// Creates a new database context from a unified <see cref="BLiteEngineOptions"/> object.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Supports the same three modes as <see cref="BLite.Core.BLiteEngine"/>:
    /// no encryption, passphrase (development), or <see cref="IKeyProvider"/> (production).
    /// </para>
    /// <para>
    /// When <see cref="EncryptionOptions.KeyProvider"/> is set this constructor blocks the
    /// calling thread via <c>GetAwaiter().GetResult()</c>.  Prefer
    /// <see cref="BuildStorageFromOptionsAsync"/> + the
    /// <see cref="DocumentDbContext(StorageEngine, EncryptionCoordinator, BLiteKvOptions)"/>
    /// constructor from an async factory method if you need to avoid a potential deadlock
    /// on a UI thread or ASP.NET synchronization context.
    /// </para>
    /// </remarks>
    /// <param name="options">Engine configuration.</param>
    protected DocumentDbContext(BLiteEngineOptions options)
    {
        if (options == null)
            throw new ArgumentNullException(nameof(options));
        if (string.IsNullOrWhiteSpace(options.Filename))
            throw new ArgumentException("BLiteEngineOptions.Filename must not be null or whitespace.", nameof(options));

        var enc = options.Encryption;

        if (enc?.KeyProvider != null && enc.Passphrase != null)
            throw new ArgumentException(
                "Specify either EncryptionOptions.Passphrase or EncryptionOptions.KeyProvider, not both.",
                nameof(options));

        if (enc != null && enc.Algorithm != EncryptionAlgorithm.AesGcm256)
            throw new NotSupportedException(
                $"Encryption algorithm '{enc.Algorithm}' is not currently supported. " +
                $"Only {nameof(EncryptionAlgorithm.AesGcm256)} is supported.");

        if (enc?.KeyProvider != null)
        {
            var databaseName = System.IO.Path.GetFileNameWithoutExtension(options.Filename);
            var keyMemory = enc.KeyProvider.GetKeyAsync(databaseName, CancellationToken.None)
                                           .GetAwaiter().GetResult();

            if (keyMemory.Length != 32)
                throw new InvalidOperationException(
                    $"IKeyProvider must return exactly 32 bytes (256-bit AES key) for database '{databaseName}'; " +
                    $"got {keyMemory.Length} bytes.");

            var masterKey = keyMemory.Span.ToArray();
            try
            {
                var coordinator = new EncryptionCoordinator(masterKey);
                try
                {
                    var mainProvider = coordinator.CreateForMainFile();
                    var config = PageFileConfig.Server(options.Filename, options.PageConfig) with
                    {
                        CryptoProvider = mainProvider
                    };
                    _storage = new StorageEngine(options.Filename, config);
                    _coordinator = coordinator;
                }
                catch
                {
                    coordinator.Dispose();
                    throw;
                }
            }
            finally
            {
                Array.Clear(masterKey, 0, masterKey.Length);
            }
        }
        else if (enc?.Passphrase != null)
        {
            var cfg = options.PageConfig;
            if (cfg.HasValue && (cfg.Value.IndexFilePath != null || cfg.Value.CollectionDataDirectory != null))
                throw new ArgumentException(
                    "EncryptionOptions.Passphrase is only supported in single-file mode. " +
                    "Use EncryptionOptions.KeyProvider for multi-file (server) mode encryption.",
                    nameof(options));

            var cryptoOptions = new CryptoOptions(enc.Passphrase, enc.Kdf, enc.KdfIterations);
            var baseConfig = options.PageConfig ?? PageFileConfig.Default;
            var config = baseConfig with
            {
                CryptoProvider = new AesGcmCryptoProvider(cryptoOptions)
            };
            _storage = new StorageEngine(options.Filename, config);
        }
        else
        {
            var config = options.PageConfig
                ?? PageFileConfig.DetectFromFile(options.Filename)
                ?? PageFileConfig.Default;
            _storage = new StorageEngine(options.Filename, config);
        }

        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, options.KvOptions);

        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
    }

    /// <summary>
    /// Creates a database context from a pre-built <see cref="StorageEngine"/> and an optional
    /// <see cref="EncryptionCoordinator"/> whose lifetime is managed by this context.
    /// </summary>
    /// <remarks>
    /// Use this constructor together with <see cref="BuildStorageFromOptionsAsync"/> to implement
    /// an async factory that properly awaits <see cref="IKeyProvider.GetKeyAsync"/>:
    /// <code>
    /// public static async Task&lt;MyDbContext&gt; CreateAsync(BLiteEngineOptions opts, CancellationToken ct = default)
    /// {
    ///     var (storage, coordinator) = await DocumentDbContext.BuildStorageFromOptionsAsync(opts, ct);
    ///     return new MyDbContext(storage, coordinator, opts.KvOptions);
    /// }
    /// </code>
    /// </remarks>
    /// <param name="storage">A fully initialised <see cref="StorageEngine"/>.</param>
    /// <param name="coordinator">
    /// The <see cref="EncryptionCoordinator"/> that owns the master key, or <c>null</c> for
    /// non-coordinator encryption modes. When non-null the context takes ownership and
    /// disposes the coordinator on <see cref="Dispose"/>.
    /// </param>
    /// <param name="kvOptions">Optional Key-Value store configuration.</param>
    protected DocumentDbContext(StorageEngine storage, EncryptionCoordinator? coordinator, BLiteKvOptions? kvOptions = null)
    {
        _storage = storage ?? throw new ArgumentNullException(nameof(storage));
        _coordinator = coordinator;
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
    }

    /// <summary>
    /// Asynchronously builds a <see cref="StorageEngine"/> from <see cref="BLiteEngineOptions"/>,
    /// properly awaiting <see cref="IKeyProvider.GetKeyAsync"/> when a key provider is configured.
    /// </summary>
    /// <remarks>
    /// Prefer this helper over the <see cref="DocumentDbContext(BLiteEngineOptions)"/> constructor
    /// when <see cref="EncryptionOptions.KeyProvider"/> is set and you are running in an environment
    /// with a synchronization context (UI thread, ASP.NET request context) where blocking on an
    /// async call could cause a deadlock.
    /// <para>
    /// The returned <see cref="EncryptionCoordinator"/> (when non-null) is owned by the caller and
    /// must be passed to a
    /// <see cref="DocumentDbContext(StorageEngine, EncryptionCoordinator, BLiteKvOptions)"/>
    /// constructor so that the context can dispose it.
    /// </para>
    /// </remarks>
    /// <param name="options">Engine configuration.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>
    /// A tuple of the initialised <see cref="StorageEngine"/> and the optional
    /// <see cref="EncryptionCoordinator"/> (non-null only for the <see cref="IKeyProvider"/> path).
    /// </returns>
    protected static async Task<(StorageEngine Storage, EncryptionCoordinator? Coordinator)>
        BuildStorageFromOptionsAsync(BLiteEngineOptions options, CancellationToken ct = default)
    {
        if (options == null)
            throw new ArgumentNullException(nameof(options));
        if (string.IsNullOrWhiteSpace(options.Filename))
            throw new ArgumentException("BLiteEngineOptions.Filename must not be null or whitespace.", nameof(options));

        var enc = options.Encryption;

        if (enc?.KeyProvider != null && enc.Passphrase != null)
            throw new ArgumentException(
                "Specify either EncryptionOptions.Passphrase or EncryptionOptions.KeyProvider, not both.",
                nameof(options));

        if (enc != null && enc.Algorithm != EncryptionAlgorithm.AesGcm256)
            throw new NotSupportedException(
                $"Encryption algorithm '{enc.Algorithm}' is not currently supported. " +
                $"Only {nameof(EncryptionAlgorithm.AesGcm256)} is supported.");

        if (enc?.KeyProvider != null)
        {
            var databaseName = System.IO.Path.GetFileNameWithoutExtension(options.Filename);
            var keyMemory = await enc.KeyProvider.GetKeyAsync(databaseName, ct).ConfigureAwait(false);

            if (keyMemory.Length != 32)
                throw new InvalidOperationException(
                    $"IKeyProvider must return exactly 32 bytes (256-bit AES key) for database '{databaseName}'; " +
                    $"got {keyMemory.Length} bytes.");

            var masterKey = keyMemory.Span.ToArray();
            try
            {
                var coordinator = new EncryptionCoordinator(masterKey);
                try
                {
                    var mainProvider = coordinator.CreateForMainFile();
                    var config = PageFileConfig.Server(options.Filename, options.PageConfig) with
                    {
                        CryptoProvider = mainProvider
                    };
                    var storage = new StorageEngine(options.Filename, config);
                    return (storage, coordinator);
                }
                catch
                {
                    coordinator.Dispose();
                    throw;
                }
            }
            finally
            {
                Array.Clear(masterKey, 0, masterKey.Length);
            }
        }

        if (enc?.Passphrase != null)
        {
            var cfg = options.PageConfig;
            if (cfg.HasValue && (cfg.Value.IndexFilePath != null || cfg.Value.CollectionDataDirectory != null))
                throw new ArgumentException(
                    "EncryptionOptions.Passphrase is only supported in single-file mode. " +
                    "Use EncryptionOptions.KeyProvider for multi-file (server) mode encryption.",
                    nameof(options));

            var cryptoOptions = new CryptoOptions(enc.Passphrase, enc.Kdf, enc.KdfIterations);
            var baseConfig = options.PageConfig ?? PageFileConfig.Default;
            var config = baseConfig with { CryptoProvider = new AesGcmCryptoProvider(cryptoOptions) };
            return (new StorageEngine(options.Filename, config), null);
        }

        {
            var config = options.PageConfig
                ?? PageFileConfig.DetectFromFile(options.Filename)
                ?? PageFileConfig.Default;
            return (new StorageEngine(options.Filename, config), null);
        }
    }

    /// <summary>
    /// Creates a database context backed by a pre-built <see cref="StorageEngine"/>.
    /// Use this constructor to supply a custom backend, such as
    /// <see cref="MemoryPageStorage"/> for in-memory or WASM scenarios.
    /// <para>
    /// Example — in-memory context:
    /// <code>
    /// var pageStorage = new MemoryPageStorage(16384);
    /// pageStorage.Open();
    /// var wal = new MemoryWriteAheadLog();
    /// var engine = new StorageEngine(pageStorage, wal);
    /// var ctx = new MyDbContext(engine);
    /// </code>
    /// </para>
    /// </summary>
    protected DocumentDbContext(StorageEngine storage, BLiteKvOptions? kvOptions = null)
    {
        _storage = storage ?? throw new ArgumentNullException(nameof(storage));
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _freeSpaceIndexes = new FreeSpaceIndexProvider(_storage);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
        DropOrphanCollections();
    }

    /// <summary>
    /// Provides access to the embedded Key-Value store that shares the same database file.
    /// </summary>
    public IBLiteKvStore KvStore
    {
        get
        {
            if (_disposed) throw new ObjectDisposedException(GetType().Name);
            return _kvStore;
        }
    }

    /// <summary>
    /// Opens a new isolated session backed by this context's storage engine.
    /// Each session carries its own independent transaction context, enabling
    /// concurrent operations from multiple callers on the same database.
    /// </summary>
    public BLiteSession OpenSession()
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        return new BLiteSession(_storage, _freeSpaceIndexes);
    }

    /// <summary>
    /// Creates a document collection bound to an explicit <paramref name="holder"/>.
    /// Use together with sessions from <see cref="OpenSession"/> so that the resulting
    /// collection's operations run inside the session's independent transaction context.
    /// </summary>
    [RequiresDynamicCode("Collection creation uses Expression.Compile() via CollectionIndexManager and ValueConverterRegistry which require dynamic code generation.")]
    [RequiresUnreferencedCode("Index creation uses reflection to access type members. Ensure all entity types and their members are preserved.")]
    public IDocumentCollection<TId, T> CreateSessionCollection<TId, T>(IDocumentMapper<TId, T> mapper, ITransactionHolder holder)
        where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        string? customName = null;
        EntityTypeBuilder<T>? builder = null;

        if (_model.TryGetValue(typeof(T), out var builderObj))
        {
            builder = builderObj as EntityTypeBuilder<T>;
            customName = builder?.CollectionName;
        }

        var collection = new DocumentCollection<TId, T>(_storage, holder, mapper, customName, _freeSpaceIndexes.GetIndex());

        if (builder != null)
        {
            if (builder.PropertyConverters.Count > 0)
                collection.SetConverterRegistry(new ValueConverterRegistry(builder.PropertyConverters));

            foreach (var indexBuilder in builder.Indexes)
                collection.ApplyIndexBuilder(indexBuilder);

            if (builder.TimeSeriesTtlField != null && builder.TimeSeriesRetention.HasValue)
                collection.SetTimeSeries(builder.TimeSeriesTtlField, builder.TimeSeriesRetention.Value);

            if (builder.RetentionPolicy != null)
                collection.SetRetentionPolicy(builder.RetentionPolicy);
        }

        return collection;
    }

    protected virtual void InitializeCollections()
    {
        // Derived classes can override to initialize collections
    }

    /// <summary>
    /// Drops any collections that exist in the underlying database but are not
    /// registered in this context. Called automatically at construction time so
    /// the database stays in sync with the schema defined by the <see cref="DocumentDbContext"/>.
    /// </summary>
    private void DropOrphanCollections()
    {
        if (_storage == null) return; // parameterless remote-context constructor

        // Build the set of collection names that this context knows about.
        var registeredNames = new HashSet<string>(
            _mapperRegistry.Values.Select(m => m.CollectionName),
            StringComparer.OrdinalIgnoreCase);

        foreach (var metadata in _storage.GetAllCollectionsMetadata())
        {
            if (registeredNames.Contains(metadata.Name)) continue;

            // Orphan — free its pages, delete its metadata, and remove any per-collection file.
            _storage.FreeCollectionPages(metadata.Name);
            _storage.DeleteCollectionMetadata(metadata.Name);
            _storage.DropCollectionFile(metadata.Name);
        }
    }

    private readonly IReadOnlyDictionary<Type, object> _model;
    private readonly List<IDocumentMapper> _registeredMappers = new();

    // Per-collection delegates registered in CreateCollection<TId, T> (called during
    // InitializeCollections, which runs on the construction thread).  These are read-only
    // after construction; no concurrent mutation occurs.
    private readonly Dictionary<Type, IDocumentMapper> _mapperRegistry = new();
    private readonly Dictionary<Type, Func<CancellationToken, Task<int>>> _truncateCallbacks = new();

    /// <summary>
    /// Override to configure the model using Fluent API.
    /// 
    /// This method is used in two phases:
    /// 1. Compile-time: The Source Generator analyzes this method to extract entity configurations
    ///    (collection names, keys, converters, etc.) and embeds them into generated mappers.
    /// 2. Runtime: Configuration is used to dynamically apply indexes to collections.
    /// 
    /// Configuration priority: ModelBuilder > Attributes > Conventions
    /// 
    /// Example:
    ///   modelBuilder.Entity&lt;Order&gt;()
    ///       .ToCollection("orders")
    ///       .HasIndex(x => x.Status);
    ///   
    ///   modelBuilder.Entity&lt;Order&gt;()
    ///       .Property(x => x.Id)
    ///       .HasConversion&lt;OrderIdConverter&gt;();
    /// </summary>
    protected virtual void OnModelCreating(ModelBuilder modelBuilder)
    {
    }

    /// <summary>
    /// Helper to create a DocumentCollection instance with custom TId.
    /// Used by derived classes in InitializeCollections for typed primary keys.
    /// </summary>
    [RequiresDynamicCode("Collection creation uses Expression.Compile() via CollectionIndexManager and ValueConverterRegistry which require dynamic code generation.")]
    [RequiresUnreferencedCode("Index creation uses reflection to access type members. Ensure all entity types and their members are preserved.")]
    protected virtual IDocumentCollection<TId, T> CreateCollection<TId, T>(IDocumentMapper<TId, T> mapper)
        where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        string? customName = null;
        EntityTypeBuilder<T>? builder = null;

        if (_model.TryGetValue(typeof(T), out var builderObj))
        {
            builder = builderObj as EntityTypeBuilder<T>;
            customName = builder?.CollectionName;
        }

        _registeredMappers.Add(mapper);
        var collection = new DocumentCollection<TId, T>(_storage, this, mapper, customName, _freeSpaceIndexes.GetIndex());

        // Apply configurations from ModelBuilder
        if (builder != null)
        {
            // Register value converters so the query engine can convert ValueObjects
            // to BSON primitives at query-plan time.
            if (builder.PropertyConverters.Count > 0)
                collection.SetConverterRegistry(new ValueConverterRegistry(builder.PropertyConverters));

            foreach (var indexBuilder in builder.Indexes)
            {
                collection.ApplyIndexBuilder(indexBuilder);
            }

            if (builder.TimeSeriesTtlField != null && builder.TimeSeriesRetention.HasValue)
                collection.SetTimeSeries(builder.TimeSeriesTtlField, builder.TimeSeriesRetention.Value);

            if (builder.RetentionPolicy != null)
                collection.SetRetentionPolicy(builder.RetentionPolicy);
        }

        _storage.RegisterMappers(_registeredMappers);

        // Register per-type delegates so TruncateCollectionAsync<T>() can operate
        // without reflection.  Populated once during InitializeCollections (single-threaded
        // constructor path) and only read on the hot path afterwards.
        _mapperRegistry[typeof(T)] = mapper;
        var col = collection;                                    // close over typed instance
        _truncateCallbacks[typeof(T)] = ct => col.TruncateAsync(ct);

        return collection;
    }

    /// <summary>
    /// Gets the document collection for the specified entity type using an ObjectId as the key.
    /// </summary>
    /// <typeparam name="T">The type of entity to retrieve the document collection for. Must be a reference type.</typeparam>
    /// <returns>An <see cref="IDocumentCollection{T}"/> instance for the specified entity type.</returns>
    public IDocumentCollection<ObjectId, T> Set<T>() where T : class => Set<ObjectId, T>();

    /// <summary>
    /// Gets a collection for managing documents of type T, identified by keys of type TId.
    /// Override is generated automatically by the Source Generator for partial DbContext classes.
    /// </summary>
    /// <typeparam name="TId">The type of the unique identifier for documents in the collection.</typeparam>
    /// <typeparam name="T">The type of the document to be managed. Must be a reference type.</typeparam>
    /// <returns>An <see cref="IDocumentCollection{TId,T}"/> instance for performing operations on documents of type T.</returns>
    public virtual IDocumentCollection<TId, T> Set<TId, T>() where T : class
    {
        throw new InvalidOperationException($"No collection registered for entity type '{typeof(T).Name}' with key type '{typeof(TId).Name}'.");
    }

    /// <summary>
    /// Deletes all documents in the collection for <typeparamref name="T"/> and clears all secondary indexes.
    /// The collection structure (schema, indexes, metadata) is preserved and the collection
    /// is immediately usable after the operation completes.
    /// </summary>
    /// <returns>Number of documents deleted.</returns>
    public async Task<int> TruncateCollectionAsync<T>(CancellationToken ct = default) where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        if (!_truncateCallbacks.TryGetValue(typeof(T), out var truncate))
            throw new InvalidOperationException($"No collection registered for entity type '{typeof(T).Name}'.");

        return await truncate(ct).ConfigureAwait(false);
    }

    // ── Metrics ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Enables the metrics subsystem. After this call, the engine starts collecting
    /// performance counters. Safe to call multiple times — idempotent.
    /// </summary>
    public void EnableMetrics(Metrics.MetricsOptions? options = null)
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        _storage.EnsureMetrics();
    }

    /// <summary>
    /// Returns an immutable point-in-time snapshot of performance counters,
    /// or <c>null</c> if <see cref="EnableMetrics"/> has not been called.
    /// </summary>
    public Metrics.MetricsSnapshot? GetMetrics()
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        return _storage.MetricsDispatcher?.GetSnapshot();
    }

    /// <summary>
    /// Returns an <see cref="IObservable{T}"/> that emits a <see cref="Metrics.MetricsSnapshot"/>
    /// at the given <paramref name="interval"/> (default 1 s).
    /// Enables the metrics subsystem automatically if not yet enabled.
    /// </summary>
    public IObservable<Metrics.MetricsSnapshot> WatchMetrics(TimeSpan? interval = null)
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        var dispatcher = _storage.EnsureMetrics();
        return new Metrics.BLiteMetricsObservable(dispatcher, interval ?? TimeSpan.FromSeconds(1));
    }

    public void Dispose()
    {
        if (_disposed)
            return;

        _disposed = true;

        _storage?.Dispose();
        _cdc?.Dispose();
        _coordinator?.Dispose();

        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Creates a new caller-owned transaction.
    /// The caller must pass this transaction to every collection method and
    /// call <see cref="SaveChangesAsync(ITransaction, CancellationToken)"/> to commit.
    /// </summary>
    public ITransaction BeginTransaction()
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        return _storage.BeginTransaction();
    }

    /// <summary>
    /// Creates a new caller-owned transaction asynchronously.
    /// </summary>
    public ValueTask<ITransaction> BeginTransactionAsync(CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        ct.ThrowIfCancellationRequested();
        return new ValueTask<ITransaction>(_storage.BeginTransaction(IsolationLevel.ReadCommitted));
    }

    /// <summary>
    /// Creates an ephemeral read transaction for internal use by collection read paths.
    /// Write paths create their own auto-commit transactions when no caller-owned tx is provided.
    /// </summary>
    public ValueTask<ITransaction> GetCurrentTransactionOrStartAsync()
    {
        return new ValueTask<ITransaction>(_storage.BeginTransaction(IsolationLevel.ReadCommitted));
    }

    /// <summary>
    /// No-op when called without a transaction.
    /// Exists for API compatibility — auto-commit write operations commit immediately.
    /// </summary>
    public ValueTask SaveChangesAsync(CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        return default;
    }

    /// <summary>
    /// Commits a caller-owned transaction created by <see cref="BeginTransactionAsync"/>.
    /// </summary>
    public async ValueTask SaveChangesAsync(ITransaction transaction, CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        if (transaction == null)
            throw new ArgumentNullException(nameof(transaction));
        await transaction.CommitAsync(ct);
    }
}
