using BLite.Core.Collections;
using BLite.Core.KeyValue;
using BLite.Core.Metadata;
using BLite.Core.Storage;
using BLite.Core.Transactions;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BLite.Bson;

namespace BLite.Core;

/// <summary>
/// Base class for database contexts.
/// Inherit and add DocumentCollection{T} properties for your entities.
/// Use partial class for Source Generator integration.
/// </summary>
public abstract partial class DocumentDbContext : IDocumentDbContext
{
    protected readonly StorageEngine _storage;
    internal readonly CDC.ChangeStreamDispatcher _cdc;
    private readonly BLiteKvStore _kvStore;
    protected bool _disposed;
    private readonly SemaphoreSlim _transactionLock = new SemaphoreSlim(1, 1);
    private ITransaction? _currentTransaction;
    public ITransaction? CurrentTransaction
    {
        get
        {
            if (_disposed)
                throw new ObjectDisposedException(nameof(DocumentDbContext));
            return _currentTransaction != null && (_currentTransaction.State == TransactionState.Active)
                ? _currentTransaction : null;
        }
        private set => _currentTransaction = value;
    }

    /// <summary>
    /// Parameterless constructor reserved for remote context subclasses generated by
    /// BLite.Client.SourceGenerators. Do <b>not</b> use this constructor for local
    /// embedded databases — the storage engine will not be initialised.
    /// </summary>
    protected DocumentDbContext()
    {
        _storage = null!;
        _cdc = null!;
        _kvStore = null!;
        _model = new System.Collections.Generic.Dictionary<Type, object>();
        InitializeCollections();
    }

    /// <summary>
    /// Creates a new database context with default configuration.
    /// Auto-detects the page size for existing database files.
    /// </summary>
    protected DocumentDbContext(string databasePath)
        : this(databasePath, PageFileConfig.DetectFromFile(databasePath) ?? PageFileConfig.Default, null)
    {
    }

    /// <summary>
    /// Creates a new database context with custom page configuration.
    /// </summary>
    protected DocumentDbContext(string databasePath, PageFileConfig config)
        : this(databasePath, config, null)
    {
    }

    /// <summary>
    /// Creates a new database context with custom Key-Value store options.
    /// </summary>
    protected DocumentDbContext(string databasePath, BLiteKvOptions kvOptions)
        : this(databasePath, PageFileConfig.Default, kvOptions)
    {
    }

    /// <summary>
    /// Creates a new database context with custom page and Key-Value store configuration.
    /// </summary>
    protected DocumentDbContext(string databasePath, PageFileConfig config, BLiteKvOptions? kvOptions)
    {
        if (string.IsNullOrWhiteSpace(databasePath))
            throw new ArgumentNullException(nameof(databasePath));

        _storage = new StorageEngine(databasePath, config);
        _cdc = new CDC.ChangeStreamDispatcher();
        _storage.RegisterCdc(_cdc);
        _kvStore = new BLiteKvStore(_storage, kvOptions);

        // Initialize model before collections
        var modelBuilder = new ModelBuilder();
        OnModelCreating(modelBuilder);
        _model = modelBuilder.GetEntityBuilders();
        InitializeCollections();
    }

    /// <summary>
    /// Provides access to the embedded Key-Value store that shares the same database file.
    /// </summary>
    public IBLiteKvStore KvStore
    {
        get
        {
            if (_disposed) throw new ObjectDisposedException(GetType().Name);
            return _kvStore;
        }
    }

    /// <summary>
    /// Opens a new isolated session backed by this context's storage engine.
    /// Each session carries its own independent transaction context, enabling
    /// concurrent operations from multiple callers on the same database.
    /// </summary>
    public BLiteSession OpenSession()
    {
        if (_disposed) throw new ObjectDisposedException(GetType().Name);
        return new BLiteSession(_storage);
    }

    /// <summary>
    /// Creates a document collection bound to an explicit <paramref name="holder"/>.
    /// Use together with sessions from <see cref="OpenSession"/> so that the resulting
    /// collection's operations run inside the session's independent transaction context.
    /// </summary>
    [RequiresDynamicCode("Collection creation uses Expression.Compile() via CollectionIndexManager and ValueConverterRegistry which require dynamic code generation.")]
    [RequiresUnreferencedCode("Index creation uses reflection to access type members. Ensure all entity types and their members are preserved.")]
    public IDocumentCollection<TId, T> CreateSessionCollection<TId, T>(IDocumentMapper<TId, T> mapper, ITransactionHolder holder)
        where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        string? customName = null;
        EntityTypeBuilder<T>? builder = null;

        if (_model.TryGetValue(typeof(T), out var builderObj))
        {
            builder = builderObj as EntityTypeBuilder<T>;
            customName = builder?.CollectionName;
        }

        var collection = new DocumentCollection<TId, T>(_storage, holder, mapper, customName);

        if (builder != null)
        {
            if (builder.PropertyConverters.Count > 0)
                collection.SetConverterRegistry(new ValueConverterRegistry(builder.PropertyConverters));

            foreach (var indexBuilder in builder.Indexes)
                collection.ApplyIndexBuilder(indexBuilder);

            if (builder.TimeSeriesTtlField != null && builder.TimeSeriesRetention.HasValue)
                collection.SetTimeSeries(builder.TimeSeriesTtlField, builder.TimeSeriesRetention.Value);
        }

        return collection;
    }

    protected virtual void InitializeCollections()
    {
        // Derived classes can override to initialize collections
    }

    private readonly IReadOnlyDictionary<Type, object> _model;
    private readonly List<IDocumentMapper> _registeredMappers = new();

    /// <summary>
    /// Override to configure the model using Fluent API.
    /// 
    /// This method is used in two phases:
    /// 1. Compile-time: The Source Generator analyzes this method to extract entity configurations
    ///    (collection names, keys, converters, etc.) and embeds them into generated mappers.
    /// 2. Runtime: Configuration is used to dynamically apply indexes to collections.
    /// 
    /// Configuration priority: ModelBuilder > Attributes > Conventions
    /// 
    /// Example:
    ///   modelBuilder.Entity&lt;Order&gt;()
    ///       .ToCollection("orders")
    ///       .HasIndex(x => x.Status);
    ///   
    ///   modelBuilder.Entity&lt;Order&gt;()
    ///       .Property(x => x.Id)
    ///       .HasConversion&lt;OrderIdConverter&gt;();
    /// </summary>
    protected virtual void OnModelCreating(ModelBuilder modelBuilder)
    {
    }

    /// <summary>
    /// Helper to create a DocumentCollection instance with custom TId.
    /// Used by derived classes in InitializeCollections for typed primary keys.
    /// </summary>
    [RequiresDynamicCode("Collection creation uses Expression.Compile() via CollectionIndexManager and ValueConverterRegistry which require dynamic code generation.")]
    [RequiresUnreferencedCode("Index creation uses reflection to access type members. Ensure all entity types and their members are preserved.")]
    protected virtual IDocumentCollection<TId, T> CreateCollection<TId, T>(IDocumentMapper<TId, T> mapper)
        where T : class
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        string? customName = null;
        EntityTypeBuilder<T>? builder = null;

        if (_model.TryGetValue(typeof(T), out var builderObj))
        {
            builder = builderObj as EntityTypeBuilder<T>;
            customName = builder?.CollectionName;
        }

        _registeredMappers.Add(mapper);
        var collection = new DocumentCollection<TId, T>(_storage, this, mapper, customName);

        // Apply configurations from ModelBuilder
        if (builder != null)
        {
            // Register value converters so the query engine can convert ValueObjects
            // to BSON primitives at query-plan time.
            if (builder.PropertyConverters.Count > 0)
                collection.SetConverterRegistry(new ValueConverterRegistry(builder.PropertyConverters));

            foreach (var indexBuilder in builder.Indexes)
            {
                collection.ApplyIndexBuilder(indexBuilder);
            }

            if (builder.TimeSeriesTtlField != null && builder.TimeSeriesRetention.HasValue)
                collection.SetTimeSeries(builder.TimeSeriesTtlField, builder.TimeSeriesRetention.Value);
        }

        _storage.RegisterMappers(_registeredMappers);

        return collection;
    }

    /// <summary>
    /// Gets the document collection for the specified entity type using an ObjectId as the key.
    /// </summary>
    /// <typeparam name="T">The type of entity to retrieve the document collection for. Must be a reference type.</typeparam>
    /// <returns>An <see cref="IDocumentCollection{T}"/> instance for the specified entity type.</returns>
    public IDocumentCollection<ObjectId, T> Set<T>() where T : class => Set<ObjectId, T>();

    /// <summary>
    /// Gets a collection for managing documents of type T, identified by keys of type TId.
    /// Override is generated automatically by the Source Generator for partial DbContext classes.
    /// </summary>
    /// <typeparam name="TId">The type of the unique identifier for documents in the collection.</typeparam>
    /// <typeparam name="T">The type of the document to be managed. Must be a reference type.</typeparam>
    /// <returns>An <see cref="IDocumentCollection{TId,T}"/> instance for performing operations on documents of type T.</returns>
    public virtual IDocumentCollection<TId, T> Set<TId, T>() where T : class
        => throw new InvalidOperationException($"No collection registered for entity type '{typeof(T).Name}' with key type '{typeof(TId).Name}'.");

    public void Dispose()
    {
        if (_disposed)
            return;

        _disposed = true;

        _storage?.Dispose();
        _cdc?.Dispose();
        _transactionLock?.Dispose();

        GC.SuppressFinalize(this);
    }

    public ITransaction BeginTransaction()
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        
        bool lockAcquired = false;
        try
        {
            if (!_transactionLock.Wait(_storage.LockTimeout.WriteTimeoutMs))
                throw new TimeoutException("Timed out acquiring transaction lock (BeginTransaction).");
            lockAcquired = true;

            if (CurrentTransaction != null)
                return CurrentTransaction; // Return existing active transaction
            CurrentTransaction = _storage.BeginTransaction();
            return CurrentTransaction;
        }
        finally
        {
            if (lockAcquired)
                _transactionLock.Release();
        }
    }

    public Task<ITransaction> BeginTransactionAsync(CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));

        // Fast path: reuse the existing transaction without touching the semaphore.
        if (CurrentTransaction != null)
            return Task.FromResult(CurrentTransaction);

        return SlowBeginTransactionAsync(ct);
    }

    private async Task<ITransaction> SlowBeginTransactionAsync(CancellationToken ct)
    {
        bool lockAcquired = false;
        try
        {
            if (!await _transactionLock.WaitAsync(_storage.LockTimeout.WriteTimeoutMs, ct))
                throw new TimeoutException("Timed out acquiring transaction lock (BeginTransactionAsync).");
            lockAcquired = true;
            
            if (CurrentTransaction != null)
                return CurrentTransaction; // Return existing active transaction
            CurrentTransaction = _storage.BeginTransaction(IsolationLevel.ReadCommitted);
            return CurrentTransaction;
        }
        finally
        {
            if (lockAcquired)
                _transactionLock.Release();
        }
    }

    public ValueTask<ITransaction> GetCurrentTransactionOrStartAsync()
    {
        var current = CurrentTransaction;
        if (current != null)
            return new ValueTask<ITransaction>(current);

        return new ValueTask<ITransaction>(SlowBeginTransactionAsync(default));
    }

    public async Task SaveChangesAsync(CancellationToken ct = default)
    {
        if (_disposed)
            throw new ObjectDisposedException(nameof(DocumentDbContext));
        if (CurrentTransaction != null)
        {
            try
            {
                await CurrentTransaction.CommitAsync(ct);
            }
            finally
            {
                CurrentTransaction = null;
            }
        }
    }
}
